import { createCipheriv, createDecipheriv, hkdfSync, randomBytes } from 'node:crypto';
import { Logger } from '@nestjs/common';

/**
 * The envelope a mailbox credential is stored in.
 *
 * ## Why this file exists at all
 *
 * A `MailAccount` row holds the password to somebody's email. That is not the
 * same class of secret as a category name: it opens their bank alerts, their
 * password resets, and every other account they own. Two consequences follow,
 * and both of them are decided here rather than at the call sites.
 *
 * **The key lives outside the backup.** `infra/deploy/40-backups.sh` dumps the
 * database and deliberately excludes `/etc/hishab/hishab.env`; that exclusion is
 * only worth anything if the thing protecting the mailbox is *in* that file and
 * nowhere else. So the key comes from `INGEST_ENCRYPTION_KEY` — generated by
 * `infra/deploy/10-provision.sh` (`openssl rand -base64 32`), listed in
 * `common/env.ts` as a value that must never be a published placeholder, and
 * until now read by nothing. A stolen dump therefore yields ciphertext and no
 * way to open it.
 *
 * **AES-256-GCM, a fresh IV per record, and the tag is kept.** Nothing here is
 * invented: GCM is authenticated encryption, the 96-bit IV is the size the mode
 * is specified for, and it is random per `encrypt()` call — an IV reused under
 * one key in GCM is catastrophic, not merely untidy, so it is never derived from
 * anything about the row.
 *
 * ## The envelope, and why the tag rides in the cipher column
 *
 * `MailAccount` has exactly two columns for this — `secretCipher` and
 * `secretIv` — and there is no third for the 16-byte authentication tag.
 * Dropping the tag was never an option: without it GCM decryption cannot tell a
 * tampered ciphertext from a real one, which turns authenticated encryption back
 * into raw counter-mode. Adding a column means a migration in a file this change
 * does not own. So the tag is stored *inside* `secretCipher`, in a versioned,
 * self-describing envelope:
 *
 * ```
 *   secretCipher = "v1." + base64(authTag) + "." + base64(ciphertext)
 *   secretIv     = base64(iv)                                   // 12 bytes
 * ```
 *
 * Base64 never emits `.`, so the split is unambiguous, and the `v1` prefix means
 * a future scheme (a real tag column, a KMS, an envelope key per workspace) can
 * be introduced beside this one and told apart on read rather than guessed at.
 *
 * ## Additional authenticated data
 *
 * Every record is sealed against `hishab.mail.secret.v1:<workspaceId>:<email>`.
 * The AAD is not secret — it is reconstructed from the row itself on read — but
 * it binds the ciphertext to the tenant it belongs to. Lifting another
 * workspace's `secretCipher`/`secretIv` pair into a row you control no longer
 * decrypts: the tag check fails and `decrypt` throws. Given that a mail
 * credential is the highest-value thing in this database, the one cross-tenant
 * move an insider could make with only UPDATE rights is worth closing.
 */

const logger = new Logger('MailCrypto');

/** The env var this module reads. Named once so the error messages agree. */
export const MAIL_KEY_ENV = 'INGEST_ENCRYPTION_KEY';

const ENVELOPE_VERSION = 'v1';

/** 96 bits — the IV size AES-GCM is specified for. Never derived, never reused. */
const IV_BYTES = 12;

/** The full 128-bit GCM tag. A truncated tag is a weaker tag for no saving. */
const TAG_BYTES = 16;

const KEY_BYTES = 32; // AES-256

/**
 * HKDF-SHA256 salt and info (RFC 5869). Constant on purpose: the derivation has
 * to be reproducible across restarts and across machines, or yesterday's rows
 * stop opening. Changing either string is a key rotation and orphans every
 * existing `secretCipher`.
 */
const HKDF_SALT = 'hishab.mail.hkdf.salt.v1';
const HKDF_INFO = 'hishab.mail.secret.v1';

/**
 * Mirrors `PLACEHOLDER_PREFIXES` in `common/env.ts`.
 *
 * TODO(main): `common/env.ts` owns this list and does not export `isPlaceholder`;
 * that file belongs to another change, so the check is duplicated rather than
 * imported. Delete this constant and import the real one once it is exported —
 * the two lists drifting apart is the only failure mode here, and it fails
 * *safe* (a placeholder this copy does not recognise still gets caught by the
 * boot check in `assertProductionEnv`).
 */
const PLACEHOLDER_PREFIXES = ['change-me', 'changeme', 'dev-', 'your-', 'replace-me', 'todo'];

function looksPublished(value: string): boolean {
  const v = value.trim().toLowerCase();
  return v === '' || PLACEHOLDER_PREFIXES.some((prefix) => v.startsWith(prefix));
}

/** Raised when a stored credential cannot be opened. Never carries key material. */
export class MailCryptoError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'MailCryptoError';
  }
}

let cachedKey: Buffer | undefined;

/**
 * The 32 bytes AES-256 is keyed with, derived once per process.
 *
 * The configured value is treated as key *material*, not as a key, and run
 * through HKDF-SHA256 to exactly 32 bytes. That is deliberate: the provisioner
 * writes base64, an operator restoring a box by hand might paste hex, and a
 * developer's `.env` holds a sentence. Requiring one encoding would turn a
 * paste-format mistake into "the mailbox feature is silently broken", and
 * accepting several encodings by sniffing them would mean the *same* secret
 * derives two different keys depending on how it parses. HKDF removes the
 * question — whatever arrives, the key is a fixed function of its bytes.
 *
 * Missing or placeholder behaves exactly as `jwtAccessSecret()` in
 * `common/env.ts` does, for the same reasons:
 *
 *  - **production** — throw. Encrypting a mailbox password under a key printed
 *    in `.env.example` is worse than not encrypting it, because the column then
 *    reads as protection to everyone who audits it.
 *  - **anywhere else** — a placeholder is used (so a checked-out repo behaves
 *    the same on every machine) and an absent value becomes a random key for
 *    this process only. Connections stored under a random key stop opening at
 *    the next restart, which is annoying and loud, and is a far better failure
 *    than a constant that looks fine.
 */
function encryptionKey(): Buffer {
  if (cachedKey !== undefined) return cachedKey;

  const configured = process.env[MAIL_KEY_ENV]?.trim();
  const isProduction = process.env.NODE_ENV === 'production';

  if (isProduction) {
    if (!configured || looksPublished(configured)) {
      throw new MailCryptoError(
        `${MAIL_KEY_ENV} is missing or still at a placeholder value. Refusing to store mailbox ` +
          'credentials under a key that is published in .env.example.',
      );
    }
  } else if (!configured) {
    logger.warn(
      `${MAIL_KEY_ENV} is not set. Using a random key for this process only; every mailbox ` +
        'credential stored now becomes unreadable when the API restarts.',
    );
  } else if (looksPublished(configured)) {
    logger.warn(
      `${MAIL_KEY_ENV} is a placeholder. Fine here, fatal in production — see mail-crypto.ts.`,
    );
  }

  const material = configured ?? randomBytes(48).toString('base64');
  cachedKey = Buffer.from(
    hkdfSync('sha256', Buffer.from(material, 'utf8'), HKDF_SALT, HKDF_INFO, KEY_BYTES),
  );
  return cachedKey;
}

/**
 * True when a credential can actually be sealed right now.
 *
 * Used by the connect endpoint so a misconfigured box answers "the server is not
 * set up to hold mailbox passwords" instead of storing something it cannot read
 * back. Never returns the key or any part of it.
 */
export function mailEncryptionAvailable(): boolean {
  try {
    encryptionKey();
    return true;
  } catch {
    return false;
  }
}

/**
 * The additional authenticated data for one mailbox.
 *
 * Reconstructed from the row on every read, so it must only use columns that
 * cannot change for the life of the record. `workspaceId` never changes and
 * `email` is the other half of the row's unique key and has no update path —
 * changing an address means disconnecting and reconnecting, which re-seals.
 */
export function mailSecretAad(workspaceId: string, email: string): string {
  return `hishab.mail.secret.v1:${workspaceId}:${email.trim().toLowerCase()}`;
}

export interface SealedSecret {
  /** `v1.<base64 tag>.<base64 ciphertext>` — goes in `MailAccount.secretCipher`. */
  cipher: string;
  /** Base64 of the 12 random bytes — goes in `MailAccount.secretIv`. */
  iv: string;
}

/** Seal a credential. A fresh IV every call; never pass one in. */
export function encryptSecret(plaintext: string, aad: string): SealedSecret {
  const key = encryptionKey();
  const iv = randomBytes(IV_BYTES);
  const cipher = createCipheriv('aes-256-gcm', key, iv, { authTagLength: TAG_BYTES });
  cipher.setAAD(Buffer.from(aad, 'utf8'));
  const body = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();

  return {
    cipher: `${ENVELOPE_VERSION}.${tag.toString('base64')}.${body.toString('base64')}`,
    iv: iv.toString('base64'),
  };
}

/**
 * Open a sealed credential, or throw.
 *
 * Every failure — wrong version, malformed envelope, wrong key, tampered
 * ciphertext, ciphertext borrowed from another tenant — comes back as the same
 * `MailCryptoError` with no detail beyond the shape of the problem. Which of
 * those it was is not information the caller can act on differently, and the
 * distinctions are exactly what a padding-oracle style probe wants.
 */
export function decryptSecret(sealed: SealedSecret, aad: string): string {
  const parts = sealed.cipher.split('.');
  if (parts.length !== 3 || parts[0] !== ENVELOPE_VERSION) {
    throw new MailCryptoError('Stored mailbox credential is not a v1 envelope');
  }

  const tag = Buffer.from(parts[1] ?? '', 'base64');
  const body = Buffer.from(parts[2] ?? '', 'base64');
  const iv = Buffer.from(sealed.iv, 'base64');
  if (tag.length !== TAG_BYTES || iv.length !== IV_BYTES) {
    throw new MailCryptoError('Stored mailbox credential has a malformed IV or auth tag');
  }

  try {
    const decipher = createDecipheriv('aes-256-gcm', encryptionKey(), iv, {
      authTagLength: TAG_BYTES,
    });
    decipher.setAAD(Buffer.from(aad, 'utf8'));
    decipher.setAuthTag(tag);
    return Buffer.concat([decipher.update(body), decipher.final()]).toString('utf8');
  } catch (err) {
    if (err instanceof MailCryptoError) throw err;
    /* `final()` throws on a failed tag check. That is the mode working, not a
     * bug: the key is wrong, the row was edited, or the blob came from another
     * workspace. The underlying message is deliberately not forwarded. */
    throw new MailCryptoError('Stored mailbox credential could not be decrypted');
  }
}
